load_test:
  duration_seconds: 3600

metrics_display:
  display_interval_ms: 5000

surrealdb:
  url: "ws://localhost:8000"
  namespace: "test"
  database: "loadtest"
  username: "root"
  password: "SecurePassword123!"

executables:
  users:
    create:
      start_delay_seconds: 0
      events_per_minute: 60
      variance_percents: 40
    read:
      start_delay_seconds: 1
      events_per_minute: 1800
      variance_percents: 20
    update:
      start_delay_seconds: 2
      events_per_minute: 120
      variance_percents: 30
    delete:
      start_delay_seconds: 3
      events_per_minute: 10
      variance_percents: 50
    get_all:
      start_delay_seconds: 4
      events_per_minute: 60
      variance_percents: 25
    page_size: 20

  follows:
    create:
      start_delay_seconds: 5
      events_per_minute: 120
      variance_percents: 30
    get_user_follows:
      start_delay_seconds: 6
      events_per_minute: 300
      variance_percents: 25
    get_user_followers:
      start_delay_seconds: 6
      events_per_minute: 300
      variance_percents: 25
    common_follows:
      start_delay_seconds: 7
      events_per_minute: 60
      variance_percents: 30
    common_followers:
      start_delay_seconds: 7
      events_per_minute: 60
      variance_percents: 30
    delete:
      start_delay_seconds: 10
      events_per_minute: 20
      variance_percents: 40
    page_size: 20